<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <TargetFrameworks>net9.0;net8.0</TargetFrameworks>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Avalonia" Version="12.1.0" />
    </ItemGroup>

    <ItemGroup>
      <AvaloniaXaml Remove="Styles\Buttons.axaml" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Themes\" />
    </ItemGroup>

</Project>
