<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <Company>TPATech.vn</Company>
	<RuntimeIdentifier>win-x64</RuntimeIdentifier>
  </PropertyGroup>

  <ItemGroup>
    <AvaloniaResource Include="Assets\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="12.1.0" />
    <PackageReference Include="Avalonia.Desktop" Version="12.1.0" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="12.1.0" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="12.1.0" />
    <PackageReference Include="AvaloniaUI.DiagnosticsSupport" Version="2.2.3">
      <IncludeAssets Condition="'$(Configuration)' != 'Debug'">None</IncludeAssets>
      <PrivateAssets Condition="'$(Configuration)' != 'Debug'">All</PrivateAssets>
    </PackageReference>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <PackageReference Include="FreeSql.Provider.MySqlConnector" Version="3.5.311" />
    <PackageReference Include="FreeSql.Provider.Sqlite" Version="3.5.311" />
    <PackageReference Include="Serilog.Sinks.File" Version="8.0.0-nblumhardt-02322" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MsBox.Avalonia\MsBox.Avalonia.csproj" />
    <ProjectReference Include="..\NCMAvaControls\NCMAvaControls.csproj" />
  </ItemGroup>
</Project>
